### ISSUE TITLE
extractMbox function fail

### ISSUE THREAD

**Issue by vectoranalytica** [jaynal83/edeR#1]
I'm trying to use this function but I ever have the same error on windows 10 in My PC and my Laptop
 
extractMbox(username=my_gmail,
+                  password=my_passwd,
+                  folder=="[Gmal]/Sent Mail",
+                  nmail=5)
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\R\R-3.6.0\library\rJython\jython.jar\Lib\imaplib.py", line 1128, in __init__
  File "C:\Program Files\R\R-3.6.0\library\rJython\jython.jar\Lib\imaplib.py", line 163, in __init__
  File "C:\Program Files\R\R-3.6.0\library\rJython\jython.jar\Lib\imaplib.py", line 1141, in open
  File "C:\Program Files\R\R-3.6.0\library\rJython\jython.jar\Lib\socket.py", line 1479, in ssl
  File "C:\Program Files\R\R-3.6.0\library\rJython\jython.jar\Lib\socket.py", line 1428, in __init__
socket.sslerror: (-1, 'SSL handshake exception')

**Comment by jaynal83** [comment]
I have tested the function in my end and it is working fine. Could you please make sure you have installed Java Runtime Environment in your pc. Also make sure you have create proper environmental variables mentioning JRE path. All of this has to be done outside R. Let me know it the error still persists.

**Comment by vectoranalytica** [comment]
Thank you so much for your time.
I'm working on Windows 10. R and RStudio and JRE were reinstalled and the
JAVA_HOME path was set. The libraries, username, and password are ready on
the environment. However, the results are the same.

> Sys.getenv("JAVA_HOME")
[1] "C:\\Program Files\\Java\\jre1.8.0_211"
> emails_sent<-edeR::extractMbox(username=sender,
+                  password=passwd,
+                  folder=="[Gmal]/Sent Mail",
+                  nmail=5)
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  :
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program
Files\R\R-3.6.0\library\rJython\jython.jar\Lib\imaplib.py", line 1128, in
__init__
  File "C:\Program
Files\R\R-3.6.0\library\rJython\jython.jar\Lib\imaplib.py", line 163, in
__init__
  File "C:\Program
Files\R\R-3.6.0\library\rJython\jython.jar\Lib\imaplib.py", line 1141, in
open
  File "C:\Program
Files\R\R-3.6.0\library\rJython\jython.jar\Lib\socket.py", line 1479, in ssl
  File "C:\Program
Files\R\R-3.6.0\library\rJython\jython.jar\Lib\socket.py", line 1428, in
__init__
socket.sslerror: (-1, 'SSL handshake exception')

Regards,

Ortiz

**Comment by jhan93** [comment]
Hi, was there any updated solution to this? This was closed about a year ago, but I am running into the same issue. I do not believe it has to do with Java setting as I can load in rJava fine and can use the xlsx library. Any help would be appreciated!

**Comment by jaynal83** [comment]
Hi, Firstly apology for delayed response. It seems that Google change changes some of the settings like "access less secure" app options. It could be due to that. If you can share your new log I will then deep dive into it. Thanks
